# Check the build status for the nighly builder, release or pull request

name: CSE7766 build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: [src/main.cpp]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('platformio.ini') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install "joaolopesf/RemoteDebug@3.0.5"
    - name: Run PlatformIO
      run: pio ci --lib="lib/CSE7766" --board=esp12e
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
#    - uses: actions/setup-node@v2
#      with:
#        node-version: '14'
#    - name: Cache Node
#      uses: actions/cache@v2
#      with:
#        path: ~/.npm
#        key: ${{ runner.os }}-${{ hashFiles('code/package-lock.json', 'code/package.json') }}
#    - name: WebUI tests
#      run: |
#        ./ci_install.sh webui
#        ./ci_script.sh webui
